services:
  web:
    build:
      context: ..
      dockerfile: docker/dockerfile
    image: malaria-detection-app:dev
    container_name: malaria-detection-app-dev
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    environment:
      - SECRET_KEY=${SECRET_KEY:-dev_secret_key}
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: python app.py
